[package]
name = "FC2Rcon"
version = "0.1.0"
authors = ["Halvor Lyche Strandvoll <halvors@halvors.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
